// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0dF15N9MNXVopT8tx0a6XHEKCl0dfzWg',
    appId: '1:394853155522:web:22103ce0c45b30f55f315b',
    messagingSenderId: '394853155522',
    projectId: 'quadlii-nhl-test',
    authDomain: 'quadlii-nhl-test.firebaseapp.com',
    storageBucket: 'quadlii-nhl-test.firebasestorage.app',
    measurementId: 'G-VKJMK5H05X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCITw9YJ2kaCoH8mRR7rfmic6AZvEOj3xs',
    appId: '1:394853155522:android:aeb2891b61695a065f315b',
    messagingSenderId: '394853155522',
    projectId: 'quadlii-nhl-test',
    storageBucket: 'quadlii-nhl-test.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJnQEnF-r5IL2NIPFjjucZw-Y8XHz71jM',
    appId: '1:394853155522:ios:f4472ae26fb83c7e5f315b',
    messagingSenderId: '394853155522',
    projectId: 'quadlii-nhl-test',
    storageBucket: 'quadlii-nhl-test.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJnQEnF-r5IL2NIPFjjucZw-Y8XHz71jM',
    appId: '1:394853155522:ios:f4472ae26fb83c7e5f315b',
    messagingSenderId: '394853155522',
    projectId: 'quadlii-nhl-test',
    storageBucket: 'quadlii-nhl-test.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0dF15N9MNXVopT8tx0a6XHEKCl0dfzWg',
    appId: '1:394853155522:web:1a81dcf1d8699a455f315b',
    messagingSenderId: '394853155522',
    projectId: 'quadlii-nhl-test',
    authDomain: 'quadlii-nhl-test.firebaseapp.com',
    storageBucket: 'quadlii-nhl-test.firebasestorage.app',
    measurementId: 'G-KSNMCJYDQD',
  );
}
